version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/dev/logs:/var/log/nginx
    ports:
      - '80:80'

  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    command: ['yarn', 'start']

  server:
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    command: ['yarn', 'start']
